---
title: "yehUtil: Personal package for some personalized Rmarkdown templates"
date: today
date-format: long
format: 
  gfm:
    preview-mode: raw
    html-math-method: 
      method: webtex
      url: https://latex.codecogs.com/png.image?%5Cbg_black&space;
---

**Chi-Kuang Yeh**  
McGill University and University of Waterloo      
      
      
## Description

This package contains some Rmarkdown templates costume for personal use. It contains:

1. A PDF format with a Table of contents with a default font size of 11pt
2. A dark theme HTML created based on rmdformats::downcute with a Table of contents and code folding option
3. A RMarkdown template for parallel computing with my own style based on the R package `lapply`
4. Template for parallel computing using the *pbapply* package

## Installation

``` r
devtools::install_github("chikuang/yehUtil")
```

## Contact or Suggestions

If you encounter any issues, please contact me [Chi-Kuang Yeh](https://chikuang.github.io/) at [chi-kuang.yeh@uwaterloo.ca](mailto:chi-kuang.yeh@uwaterloo.ca) or [chi-kuang.yeh@mail.mcgill.ca](mailto:chi-kuang.yeh@mail.mcgill.ca).  

## TODO

+ [ ] Add more details 
